version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: project-mysql
    restart: unless-stopped

    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: social_training
      MYSQL_USER: app
      MYSQL_PASSWORD: app123

    ports:
      - "3307:3306"

    # 统一字符集，避免中文/表情问题
    command:
      [
        "mysqld",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_0900_ai_ci"
      ]

    volumes:
      # 持久化数据（删容器不会丢库）
      - mysql_data:/var/lib/mysql
      # 初始化脚本（建表、插数据等）
      - ./db-init:/docker-entrypoint-initdb.d:ro

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-proot123"]
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  mysql_data:
